title = "test"

[[constraint]]
  branch = "master"
  name = "github.com/axgle/mahonia"

[[constraint]]
  name = "github.com/labstack/echo"
  version = "3.2.5"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.7.1"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"

